# 数据划分比例
data_split:
  day_flag: false
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  sampling_method: hour_14

# 数据加载器配置
dataloader:
  batch_size: 32
  interval_length: 1656
  input_length: 84
  output_length: 1

# 模型配置
model:
  use_rolling: true
  num_blocks: 2
  dim: 128

# 训练配置
training:
  epochs: 120
  loss_function: 'Huber'
  loss_para: 1.0
  clip_v: 0.5
  optimizer:
    learning_rate: 0.001
    weight_decay: 0.01

# 数据预处理
preprocessing:
  scalar: true
  scalar_contain_labels: true
  target_value: 'I_P'
  outlier_flag: true
  interpolation: true
  features_num: 4
  lag_points: 84
  Otl_Plt_M: 'sigma'
  threshold: 3.0
  limit: 3

# 数据路径
paths:
  # 异常去除
  data_directory: "E:/data/full_lines1/"
  input_file: "E:\\code\\mission\\full_sampled_lines.csv"
